# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(987, 753)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Icon/Восток-Амур-Сервис.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1,\n"
"  stop:0 #4158D0,\n"
"  stop:0.46 #C850C0,\n"
"  stop:1 #4B1061);\n"
"\n"
"font-family:Cambria\n"
"\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.MainTheme = QtWidgets.QWidget(self.centralwidget)
        self.MainTheme.setStyleSheet("")
        self.MainTheme.setObjectName("MainTheme")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.MainTheme)
        self.horizontalLayout_10.setContentsMargins(12, 12, 12, 12)
        self.horizontalLayout_10.setSpacing(12)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.balance_widget = QtWidgets.QFrame(self.MainTheme)
        self.balance_widget.setStyleSheet("background-color:rgba(255,255,255,70);\n"
"border: 1px solid rgba(255,255,255,40);\n"
"border-radius: 7px;")
        self.balance_widget.setObjectName("balance_widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.balance_widget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_currentbalance = QtWidgets.QLabel(self.balance_widget)
        self.label_currentbalance.setStyleSheet("color:white;\n"
"font-weight:bold;\n"
"font-size:20pt;\n"
"background-color:none;\n"
"border:none")
        self.label_currentbalance.setObjectName("label_currentbalance")
        self.verticalLayout.addWidget(self.label_currentbalance)
        self.label_balance = QtWidgets.QLabel(self.balance_widget)
        self.label_balance.setStyleSheet("color:white;\n"
"font-size:30pt;\n"
"font-weight:bold;\n"
"border:none;\n"
"background-color:none;")
        self.label_balance.setObjectName("label_balance")
        self.verticalLayout.addWidget(self.label_balance)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.icon_up_arrow = QtWidgets.QLabel(self.balance_widget)
        self.icon_up_arrow.setMinimumSize(QtCore.QSize(0, 0))
        self.icon_up_arrow.setMaximumSize(QtCore.QSize(30, 30))
        self.icon_up_arrow.setBaseSize(QtCore.QSize(0, 0))
        self.icon_up_arrow.setStyleSheet("background-color:none;\n"
"border:none;\n"
"padding-top:10px;")
        self.icon_up_arrow.setText("")
        self.icon_up_arrow.setPixmap(QtGui.QPixmap(":/newPrefix/north_west_white_24dp.svg"))
        self.icon_up_arrow.setObjectName("icon_up_arrow")
        self.horizontalLayout.addWidget(self.icon_up_arrow)
        self.label_doxod = QtWidgets.QLabel(self.balance_widget)
        self.label_doxod.setStyleSheet("color:white;\n"
"font-weight:bold;\n"
"font-size:16pt;\n"
"background-color:none;\n"
"border:none;")
        self.label_doxod.setObjectName("label_doxod")
        self.horizontalLayout.addWidget(self.label_doxod)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.income_balance = QtWidgets.QLabel(self.balance_widget)
        self.income_balance.setStyleSheet("color:white;\n"
"font-size:20pt;\n"
"background-color:none;\n"
"border:none")
        self.income_balance.setObjectName("income_balance")
        self.verticalLayout.addWidget(self.income_balance)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_6 = QtWidgets.QLabel(self.balance_widget)
        self.label_6.setMaximumSize(QtCore.QSize(30, 30))
        self.label_6.setStyleSheet("background-color:none;\n"
"border:none;\n"
"padding-top:10px;")
        self.label_6.setText("")
        self.label_6.setTextFormat(QtCore.Qt.AutoText)
        self.label_6.setPixmap(QtGui.QPixmap(":/newPrefix/call_received_white_24dp.svg"))
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_2.addWidget(self.label_6)
        self.label_rasxod = QtWidgets.QLabel(self.balance_widget)
        self.label_rasxod.setStyleSheet("color:white;\n"
"font-weight:bold;\n"
"font-size:16pt;\n"
"background-color:none;\n"
"border:none;")
        self.label_rasxod.setObjectName("label_rasxod")
        self.horizontalLayout_2.addWidget(self.label_rasxod)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.outcome_balance = QtWidgets.QLabel(self.balance_widget)
        self.outcome_balance.setStyleSheet("color:white;\n"
"font-size:20pt;\n"
"background-color:none;\n"
"border:none")
        self.outcome_balance.setObjectName("outcome_balance")
        self.verticalLayout.addWidget(self.outcome_balance)
        self.horizontalLayout_10.addWidget(self.balance_widget)
        self.categories_frame = QtWidgets.QFrame(self.MainTheme)
        self.categories_frame.setStyleSheet("background-color:rgba(255,255,255,70);\n"
"border: 1px solid rgba(255,255,255,40);\n"
"border-radius: 7px;")
        self.categories_frame.setObjectName("categories_frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.categories_frame)
        self.verticalLayout_2.setContentsMargins(12, 12, 12, 12)
        self.verticalLayout_2.setSpacing(12)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_categories = QtWidgets.QLabel(self.categories_frame)
        self.label_categories.setStyleSheet("color:white;\n"
"font-weight:bold;\n"
"font-size:20pt;\n"
"background-color:none;\n"
"border:none\n"
"")
        self.label_categories.setObjectName("label_categories")
        self.verticalLayout_2.addWidget(self.label_categories)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_10 = QtWidgets.QLabel(self.categories_frame)
        self.label_10.setMinimumSize(QtCore.QSize(0, 0))
        self.label_10.setMaximumSize(QtCore.QSize(30, 30))
        self.label_10.setSizeIncrement(QtCore.QSize(0, 0))
        self.label_10.setBaseSize(QtCore.QSize(0, 0))
        self.label_10.setStyleSheet("background-color:none;\n"
"border:none;")
        self.label_10.setText("")
        self.label_10.setPixmap(QtGui.QPixmap(":/newPrefix/icons8-clothes-48.png"))
        self.label_10.setScaledContents(True)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_9.addWidget(self.label_10)
        self.label_11 = QtWidgets.QLabel(self.categories_frame)
        self.label_11.setStyleSheet("color:white;\n"
"font-weight:bold;\n"
"font-size:14pt;\n"
"background-color:none;\n"
"border:none;")
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_9.addWidget(self.label_11)
        self.balance_odeshda = QtWidgets.QLabel(self.categories_frame)
        self.balance_odeshda.setStyleSheet("color:white;\n"
"font-weight:bold;\n"
"font-size:14pt;\n"
"background-color:none;\n"
"border:none;")
        self.balance_odeshda.setObjectName("balance_odeshda")
        self.horizontalLayout_9.addWidget(self.balance_odeshda)
        self.verticalLayout_2.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_13 = QtWidgets.QLabel(self.categories_frame)
        self.label_13.setMaximumSize(QtCore.QSize(30, 30))
        self.label_13.setStyleSheet("background-color:none;\n"
"border:none;")
        self.label_13.setText("")
        self.label_13.setPixmap(QtGui.QPixmap(":/newPrefix/icons8-boots-48.png"))
        self.label_13.setScaledContents(True)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_8.addWidget(self.label_13)
        self.label_14 = QtWidgets.QLabel(self.categories_frame)
        self.label_14.setStyleSheet("color:white;\n"
"font-weight:bold;\n"
"font-size:14pt;\n"
"background-color:none;\n"
"border:none;")
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_8.addWidget(self.label_14)
        self.balance_obyv = QtWidgets.QLabel(self.categories_frame)
        self.balance_obyv.setStyleSheet("color:white;\n"
"font-weight:bold;\n"
"font-size:14pt;\n"
"background-color:none;\n"
"border:none;")
        self.balance_obyv.setObjectName("balance_obyv")
        self.horizontalLayout_8.addWidget(self.balance_obyv)
        self.verticalLayout_2.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_16 = QtWidgets.QLabel(self.categories_frame)
        self.label_16.setMaximumSize(QtCore.QSize(30, 30))
        self.label_16.setStyleSheet("background-color:none;\n"
"border:none;")
        self.label_16.setText("")
        self.label_16.setPixmap(QtGui.QPixmap(":/newPrefix/icons8-helmet-48.png"))
        self.label_16.setScaledContents(True)
        self.label_16.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_7.addWidget(self.label_16)
        self.label_17 = QtWidgets.QLabel(self.categories_frame)
        self.label_17.setStyleSheet("color:white;\n"
"font-weight:bold;\n"
"font-size:12pt;\n"
"background-color:none;\n"
"border:none;")
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_7.addWidget(self.label_17)
        self.balance_sredstva_zashit = QtWidgets.QLabel(self.categories_frame)
        self.balance_sredstva_zashit.setStyleSheet("color:white;\n"
"font-weight:bold;\n"
"font-size:14pt;\n"
"background-color:none;\n"
"border:none;")
        self.balance_sredstva_zashit.setObjectName("balance_sredstva_zashit")
        self.horizontalLayout_7.addWidget(self.balance_sredstva_zashit)
        self.verticalLayout_2.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_19 = QtWidgets.QLabel(self.categories_frame)
        self.label_19.setMaximumSize(QtCore.QSize(30, 30))
        self.label_19.setStyleSheet("background-color:none;\n"
"border:none;")
        self.label_19.setText("")
        self.label_19.setPixmap(QtGui.QPixmap(":/newPrefix/icons8-glove-48.png"))
        self.label_19.setScaledContents(True)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_6.addWidget(self.label_19)
        self.label_20 = QtWidgets.QLabel(self.categories_frame)
        self.label_20.setStyleSheet("color:white;\n"
"font-weight:bold;\n"
"font-size:14pt;\n"
"background-color:none;\n"
"border:none;")
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_6.addWidget(self.label_20)
        self.balance_ryki = QtWidgets.QLabel(self.categories_frame)
        self.balance_ryki.setStyleSheet("color:white;\n"
"font-weight:bold;\n"
"font-size:14pt;\n"
"background-color:none;\n"
"border:none;")
        self.balance_ryki.setObjectName("balance_ryki")
        self.horizontalLayout_6.addWidget(self.balance_ryki)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_22 = QtWidgets.QLabel(self.categories_frame)
        self.label_22.setMaximumSize(QtCore.QSize(30, 30))
        self.label_22.setStyleSheet("background-color:none;\n"
"border:none;")
        self.label_22.setText("")
        self.label_22.setPixmap(QtGui.QPixmap(":/newPrefix/icons8-vending-64.png"))
        self.label_22.setScaledContents(True)
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_5.addWidget(self.label_22)
        self.label_24 = QtWidgets.QLabel(self.categories_frame)
        self.label_24.setStyleSheet("color:white;\n"
"font-weight:bold;\n"
"font-size:14pt;\n"
"background-color:none;\n"
"border:none;")
        self.label_24.setObjectName("label_24")
        self.horizontalLayout_5.addWidget(self.label_24)
        self.balance_vending = QtWidgets.QLabel(self.categories_frame)
        self.balance_vending.setStyleSheet("color:white;\n"
"font-weight:bold;\n"
"font-size:14pt;\n"
"background-color:none;\n"
"border:none;")
        self.balance_vending.setObjectName("balance_vending")
        self.horizontalLayout_5.addWidget(self.balance_vending)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_25 = QtWidgets.QLabel(self.categories_frame)
        self.label_25.setMaximumSize(QtCore.QSize(30, 30))
        self.label_25.setStyleSheet("background-color:none;\n"
"border:none;")
        self.label_25.setText("")
        self.label_25.setPixmap(QtGui.QPixmap(":/newPrefix/icons8-exoskeleton-64.png"))
        self.label_25.setScaledContents(True)
        self.label_25.setObjectName("label_25")
        self.horizontalLayout_4.addWidget(self.label_25)
        self.label_27 = QtWidgets.QLabel(self.categories_frame)
        self.label_27.setStyleSheet("color:white;\n"
"font-weight:bold;\n"
"font-size:14pt;\n"
"background-color:none;\n"
"border:none;")
        self.label_27.setObjectName("label_27")
        self.horizontalLayout_4.addWidget(self.label_27)
        self.balance_exoskeleton = QtWidgets.QLabel(self.categories_frame)
        self.balance_exoskeleton.setStyleSheet("color:white;\n"
"font-weight:bold;\n"
"font-size:14pt;\n"
"background-color:none;\n"
"border:none;")
        self.balance_exoskeleton.setObjectName("balance_exoskeleton")
        self.horizontalLayout_4.addWidget(self.balance_exoskeleton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_28 = QtWidgets.QLabel(self.categories_frame)
        self.label_28.setMaximumSize(QtCore.QSize(30, 30))
        self.label_28.setStyleSheet("background-color:none;\n"
"border:none;")
        self.label_28.setText("")
        self.label_28.setPixmap(QtGui.QPixmap(":/newPrefix/icons8-cone-64.png"))
        self.label_28.setScaledContents(True)
        self.label_28.setObjectName("label_28")
        self.horizontalLayout_3.addWidget(self.label_28)
        self.label_30 = QtWidgets.QLabel(self.categories_frame)
        self.label_30.setStyleSheet("color:white;\n"
"font-weight:bold;\n"
"font-size:14pt;\n"
"background-color:none;\n"
"border:none;")
        self.label_30.setObjectName("label_30")
        self.horizontalLayout_3.addWidget(self.label_30)
        self.balance_other = QtWidgets.QLabel(self.categories_frame)
        self.balance_other.setStyleSheet("color:white;\n"
"font-weight:bold;\n"
"font-size:14pt;\n"
"background-color:none;\n"
"border:none;")
        self.balance_other.setObjectName("balance_other")
        self.horizontalLayout_3.addWidget(self.balance_other)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_10.addWidget(self.categories_frame)
        self.verticalLayout_3.addWidget(self.MainTheme)
        self.my_buttons = QtWidgets.QFrame(self.centralwidget)
        self.my_buttons.setObjectName("my_buttons")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.my_buttons)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.btn_new_zakaz = QtWidgets.QPushButton(self.my_buttons)
        self.btn_new_zakaz.setStyleSheet("QPushButton {\n"
"font-size:22px;\n"
"color: white;\n"
"background-color:rgba(255,255,255,30);\n"
"border: 1px solid rgba(255,255,255,40);\n"
"border-radius:7px;\n"
"width:230px;\n"
"height:50px\n"
"}    \n"
"QPushButton::hover{\n"
"background-color:rgba(255,255,255,50);\n"
"}\n"
"\n"
"QPushButton::pressed{\n"
"background-color:rgba(255,255,255,70);\n"
"}\n"
"")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/newPrefix/icons8-database-60.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_new_zakaz.setIcon(icon1)
        self.btn_new_zakaz.setIconSize(QtCore.QSize(30, 30))
        self.btn_new_zakaz.setShortcut("")
        self.btn_new_zakaz.setObjectName("btn_new_zakaz")
        self.horizontalLayout_11.addWidget(self.btn_new_zakaz)
        self.btn_change_data = QtWidgets.QPushButton(self.my_buttons)
        self.btn_change_data.setStyleSheet("QPushButton {\n"
"font-size:22px;\n"
"color: white;\n"
"background-color:rgba(255,255,255,30);\n"
"border: 1px solid rgba(255,255,255,40);\n"
"border-radius:7px;\n"
"width:230px;\n"
"height:50px\n"
"}    \n"
"QPushButton::hover{\n"
"background-color:rgba(255,255,255,50);\n"
"}\n"
"\n"
"QPushButton::pressed{\n"
"background-color:rgba(255,255,255,70);\n"
"}\n"
"")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/newPrefix/icons8-replace-100.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_change_data.setIcon(icon2)
        self.btn_change_data.setIconSize(QtCore.QSize(30, 30))
        self.btn_change_data.setObjectName("btn_change_data")
        self.horizontalLayout_11.addWidget(self.btn_change_data)
        self.btn_delete_zakaz = QtWidgets.QPushButton(self.my_buttons)
        self.btn_delete_zakaz.setStyleSheet("QPushButton {\n"
"font-size:22px;\n"
"color: white;\n"
"background-color:rgba(255,255,255,30);\n"
"border: 1px solid rgba(255,255,255,40);\n"
"border-radius:7px;\n"
"width:230px;\n"
"height:50px\n"
"}    \n"
"QPushButton::hover{\n"
"background-color:rgba(255,255,255,50);\n"
"}\n"
"\n"
"QPushButton::pressed{\n"
"background-color:rgba(255,255,255,70);\n"
"}\n"
"")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/newPrefix/icons8-delete-48.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_delete_zakaz.setIcon(icon3)
        self.btn_delete_zakaz.setIconSize(QtCore.QSize(30, 30))
        self.btn_delete_zakaz.setObjectName("btn_delete_zakaz")
        self.horizontalLayout_11.addWidget(self.btn_delete_zakaz)
        self.verticalLayout_3.addWidget(self.my_buttons)
        self.tableView = QtWidgets.QTableView(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableView.sizePolicy().hasHeightForWidth())
        self.tableView.setSizePolicy(sizePolicy)
        self.tableView.setStyleSheet("QTableView {\n"
"font-size: 11pt;\n"
"background-color: rgba(255, 255, 255, 30); \n"
"border: 1px solid rgba(255,255,255,40);\n"
"border-bottom-right-radius: 7px; \n"
"border-bottom-left-radius: 7px; \n"
"color: white;\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"background-color: rgb(53, 53, 53);\n"
"color: white;\n"
"border: none;\n"
"height: 50px;\n"
"font-size: 16pt;\n"
"}\n"
"\n"
"QTableView::item {\n"
"    border-style: none;\n"
"    border-bottom: 1px solid rgba(255,255,255,50);\n"
"    padding-left: auto;\n"
"    padding-right: auto;\n"
"}\n"
"\n"
"QTableView::item:selected{\n"
"    border: none;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 50);\n"
"}\n"
"")
        self.tableView.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableView.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableView.setShowGrid(False)
        self.tableView.setObjectName("tableView")
        self.tableView.horizontalHeader().setDefaultSectionSize(155)
        self.tableView.horizontalHeader().setMinimumSectionSize(70)
        self.tableView.horizontalHeader().setSortIndicatorShown(True)
        self.tableView.verticalHeader().setVisible(False)
        self.tableView.verticalHeader().setDefaultSectionSize(50)
        self.verticalLayout_3.addWidget(self.tableView)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Восток-Сервис-Амур"))
        self.label_currentbalance.setText(_translate("MainWindow", "Бюджет"))
        self.label_balance.setText(_translate("MainWindow", "10 Р"))
        self.label_doxod.setText(_translate("MainWindow", "Доход"))
        self.income_balance.setText(_translate("MainWindow", "10 Р"))
        self.label_rasxod.setText(_translate("MainWindow", "Расход"))
        self.outcome_balance.setText(_translate("MainWindow", "10 Р"))
        self.label_categories.setText(_translate("MainWindow", "Категории товара"))
        self.label_11.setText(_translate("MainWindow", "Спецодежда"))
        self.balance_odeshda.setText(_translate("MainWindow", "Сумма"))
        self.label_14.setText(_translate("MainWindow", "Спецобувь"))
        self.balance_obyv.setText(_translate("MainWindow", "Сумма"))
        self.label_17.setText(_translate("MainWindow", "Средства защиты"))
        self.balance_sredstva_zashit.setText(_translate("MainWindow", "Сумма"))
        self.label_20.setText(_translate("MainWindow", "Защита рук"))
        self.balance_ryki.setText(_translate("MainWindow", "Сумма"))
        self.label_24.setText(_translate("MainWindow", " Вендинг"))
        self.balance_vending.setText(_translate("MainWindow", "Сумма"))
        self.label_27.setText(_translate("MainWindow", "Экзоскелеты"))
        self.balance_exoskeleton.setText(_translate("MainWindow", "Сумма"))
        self.label_30.setText(_translate("MainWindow", "Другое"))
        self.balance_other.setText(_translate("MainWindow", "Сумма"))
        self.btn_new_zakaz.setText(_translate("MainWindow", "Новый заказ"))
        self.btn_change_data.setText(_translate("MainWindow", "Редактировать запись"))
        self.btn_delete_zakaz.setText(_translate("MainWindow", "Удалить запись"))
import IconsPackage_rc
